### ISSUE TITLE
Question: Is it possible to call `process_render_frame` multiple times for different streams? 

### ISSUE THREAD

**Issue by morajabi** [tonarino/webrtc-audio-processing#32]
In a multi-peer voice call, you want to cancel echo from all streams. There is two ways:
1. mix the output, then call `processor.process_render_frame` once
2. call it multiple times on each tick per output stream

Which one is advised?

**Comment by strohel** [comment]
We (I) cannot claim we're experts on the inner workings (in the end this crate is just a wrapper around the upstream code), but 1. (mixing all output into one stream before feeting to AEC) seems like the right way to do it.

**Comment by skywhale** [comment]
As @strohel mentioned, (1) is the way to go.

More specifically, you want to be feeding the AEC with the stream that is closest to how it's fed to the playback device i.e. after all the processing and mixing.

Please reopen if you have follow-up questions :)
