### ISSUE TITLE
What's blocking using latest freedesktop/pulseaudio-webrtc-audio-processing?

### ISSUE THREAD

**Issue by morajabi** [tonarino/webrtc-audio-processing#33]
I see #23 but unsure what happened afterwards. Is there anything I can do to unblock having latest code for the AudioProcessing in?

**Comment by bschwind** [comment]
Hi @morajabi , overall I don't think there is anything blocking it. It's been over a year at this point, but I do remember when we tried a newer version we weren't very impressed with its performance. We should of course try again and be more thorough in our testing.

We definitely want to get this to bind to the latest upstream version, I'm just not sure on timing yet. Happy to do any code reviews though if you want to take a stab at it!
